default: # default connection
  host: 'localhost'
  port: 5432
  username: 'postgres'
  password: 'postgres'
  database: 'postgres'
  type: postgres
  synchronize: false,
  entities:
    - src/models/*.ts
  migrations:
    - src/migrations/*.ts
  cli:
    migrationsDir: src/migrations
