default: # default connection
  host: 'localhost'
  port: 5432
  username: 'postgres'
  password: 'postgres'
  database: 'postgres'
  type: postgres
  synchronize: true,
  entities:
    - dist/models/*.js
  migrations:
    - dist/migrations/*.js
  cli:
    migrationsDir: src/migrations
